<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Book a call_insent-popup-card-close-icon</name>
   <tag></tag>
   <elementGuidId>0d322767-4b01-495f-8d02-8a2b9ae750af</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='insent-popup-card-close-icon']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#insent-popup-card-close-icon</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#insent-popup-card-close-icon</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>6bae4af6-17ca-4cd9-b817-af38d28c7425</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>insent-popup-card-close-icon</value>
      <webElementGuid>d498391c-dc1d-407b-b9cb-1ab573472bd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/static/media/close.ec75d473.svg</value>
      <webElementGuid>04e6f583-94e1-4ee7-9d65-f976b1f0e00b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-cEvuZC gxfXwW</value>
      <webElementGuid>48cb3438-a0e7-46fa-9aa8-db5933820ee0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;insent-popup-card-close-icon&quot;)</value>
      <webElementGuid>bc4c4b5d-a2c2-437c-a677-12c1453ef5dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/GithubPro/Page_Katalon Studio Easy Test Automation fo_c94398/iframe_concat(id(, , insent-iframe, , ))_in_d2847a</value>
      <webElementGuid>85af72df-c335-4893-8cd5-28745a4fda05</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='insent-popup-card-close-icon']</value>
      <webElementGuid>e324c7a4-bf87-4e36-b8bb-549bb2a16b8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='insent-popup-card-close']/img</value>
      <webElementGuid>c1e28d85-8c90-4b50-9f63-16fe8b1ff667</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/img</value>
      <webElementGuid>d3cdf109-fa3d-406c-b60c-57e1620bd3ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = 'insent-popup-card-close-icon' and @src = '/static/media/close.ec75d473.svg']</value>
      <webElementGuid>764bea54-b123-4587-81ef-78a7306e8409</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
