<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Write Your Review_review</name>
   <tag></tag>
   <elementGuidId>507fd8f7-a97a-47eb-bb62-8314a682d75c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#review</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='review']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Add Review Here!&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>eb85c117-ed11-4c77-9a3f-30bfdc82328c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>review</value>
      <webElementGuid>49f599f3-f8ca-4e9c-82f0-5cf9e691e8da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Add Review Here!</value>
      <webElementGuid>1d90fd88-f605-4dc3-8a9d-278b953738ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>review</value>
      <webElementGuid>0ac0ac22-4be9-4f71-b70b-7b1e0ccec519</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;review&quot;)</value>
      <webElementGuid>c5c6625e-3817-46f4-afcf-306bc127a45e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='review']</value>
      <webElementGuid>cc68ea17-5018-4689-ad82-dcfd5ccb5308</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='review-form']/textarea</value>
      <webElementGuid>c3e7addd-497c-4087-965e-ace31015d36c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>319b2c54-8440-49df-a82f-0135fb6b6bb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'review' and @placeholder = 'Add Review Here!' and @id = 'review']</value>
      <webElementGuid>b02417f2-d1ae-4eaf-bca5-cc10823afed9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
