<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__mobile_number</name>
   <tag></tag>
   <elementGuidId>cf14c859-df57-4cef-9153-1302ee30619e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mobile_number</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='mobile_number']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Mobile Number *&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b39da83a-d083-481b-987a-8b74285f8868</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f62fbda5-460f-4307-8b7e-d6f75185aa02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-qa</name>
      <type>Main</type>
      <value>mobile_number</value>
      <webElementGuid>45463691-bbc2-4670-ba9a-6d6a8a2f3b9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>4bd33836-3a97-46d7-a860-acec50c296ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>mobile_number</value>
      <webElementGuid>14842118-63c3-4e09-bc58-9e398a03dc63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mobile_number</value>
      <webElementGuid>f2698ec7-edcf-47a7-8344-775a5c5d901d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mobile_number&quot;)</value>
      <webElementGuid>cfd30eba-eea6-4c4c-9d97-c11c45e2de24</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='mobile_number']</value>
      <webElementGuid>ddcf8d4e-2b70-426f-ab40-2cf9b6f19335</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='form']/div/div/div/div/form/p[10]/input</value>
      <webElementGuid>85213219-5073-449c-8e98-fb8ed201f89d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[10]/input</value>
      <webElementGuid>c02883fa-00cc-4815-9788-c726bc2a414b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'mobile_number' and @id = 'mobile_number']</value>
      <webElementGuid>42cdc4d4-346b-4a9c-be3b-a001e58de965</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
